export { install } from './install'
export type { InstallOptions, InstallResult } from './install'
export { uninstall } from './uninstall'
export type { UninstallOptions } from './uninstall'
export { run } from './run'
export { renderTemplate, buildCronLine } from './render'
export { upsertSshHost, hasSshHost, renderHostBlock } from './ssh-config'
export { parseDevboxHost, detectDevboxHost, findTailscale } from './tailscale'
export type { PeerHost } from './tailscale'
